/**
 * Razorpay plan ID resolver + pricing constants.
 *
 * Plan IDs are stored in environment variables (generated by
 * src/scripts/create-razorpay-plans.ts) rather than in the DB.
 * This makes plan configuration explicit and reproducible from code.
 *
 * Plan structure:
 *   3 slugs (individual, team, business)
 *   × 2 currencies (USD, INR)
 *   × 2 cycles (monthly, annual)
 *   = 12 plans total
 */

export type PlanSlug = 'individual' | 'team' | 'business';
export type BillingCycle = 'monthly' | 'annual';
export type Currency = 'USD' | 'INR';

/**
 * Resolve the Razorpay plan ID for a given slug, cycle, and currency.
 * Throws clearly if the corresponding env var is missing.
 */
export function getPlanId(slug: PlanSlug, cycle: BillingCycle, currency: Currency): string {
  const key = `RAZORPAY_PLAN_${slug.toUpperCase()}_${currency}_${cycle.toUpperCase()}`;
  const id = process.env[key];
  if (!id) {
    if (currency === 'USD') {
      throw new Error(
        `USD plans not configured. Enable International Payments in Razorpay dashboard, ` +
        `then run: npx tsx src/scripts/create-razorpay-plans.ts`,
      );
    }
    throw new Error(`Missing env var: ${key} — run src/scripts/create-razorpay-plans.ts first`);
  }
  return id;
}

/**
 * Reverse-lookup: given a Razorpay plan ID from a webhook, return the plan slug.
 * Scans all 12 env vars. Returns null if not found.
 */
export function planSlugFromPlanId(planId: string): PlanSlug | null {
  const slugs: PlanSlug[] = ['individual', 'team', 'business'];
  const currencies: Currency[] = ['USD', 'INR'];
  const cycles: BillingCycle[] = ['monthly', 'annual'];

  for (const slug of slugs) {
    for (const currency of currencies) {
      for (const cycle of cycles) {
        const key = `RAZORPAY_PLAN_${slug.toUpperCase()}_${currency}_${cycle.toUpperCase()}`;
        if (process.env[key] === planId) return slug;
      }
    }
  }
  return null;
}

/**
 * Pricing display values — single source of truth for UI and API.
 * Monthly amounts are per-unit. Annual amounts are per-unit per-month
 * (i.e. the annual total divided by 12 for display purposes).
 */
export const PLAN_PRICING = {
  individual: {
    usd_monthly:  10,
    usd_annual:    8,   // $96/yr billed annually
    inr_monthly: 899,
    inr_annual:  675,   // ₹8,099/yr billed annually
  },
  team: {
    usd_monthly:  15,
    usd_annual:   12,   // $144/yr billed annually
    inr_monthly: 999,
    inr_annual:  749,   // ₹8,991/yr billed annually
  },
  business: {
    usd_monthly:  24,
    usd_annual:   20,   // $240/yr billed annually
    inr_monthly: 1999,
    inr_annual:  1499,  // ₹17,991/yr billed annually
  },
} as const;

/** Annual totals (what Razorpay actually charges once a year). */
export const ANNUAL_TOTALS = {
  individual: { usd: 96,   inr: 8099  },
  team:       { usd: 144,  inr: 8991  },
  business:   { usd: 240,  inr: 17991 },
} as const;
