// Types for the public /prep placement question bank. Data is generated by
// scripts/build-prep-data.mjs into src/data/prep-questions.json.

export interface InterviewQ {
  id: string;
  company: string;
  role: string | null;
  category: string;            // HR / Fit · Technical · Situational · Case / Domain
  question: string;
  answerMarkdown: string;
  source: string | null;
  topic: string | null;
}

export interface AptitudeOption {
  label: string;               // A | B | C | D
  text: string;
  correct: boolean;
}

export interface AptitudeQ {
  id: string;
  company: string;
  section: string;             // Quantitative · Logical Reasoning · Verbal · …
  type: 'mcq' | 'open';
  question: string;
  promptMarkdown: string | null;   // table / sub-question shown above MCQ options
  options: AptitudeOption[] | null;
  solutionMarkdown: string | null;
  answerMarkdown: string | null;   // for open / coding questions
  source: string | null;
  topic: string | null;
}

export interface PrepData {
  meta: {
    generatedFrom: string[];
    counts: { interview: number; aptitude: number; aptitudeMcq: number; aptitudeOpen: number };
    interviewCompanies: string[];
    aptitudeCompanies: string[];
    interviewCategories: string[];
    aptitudeSections: string[];
  };
  interview: InterviewQ[];
  aptitude: AptitudeQ[];
  overviews: Record<string, string>;
  patterns: Record<string, string>;
}

export type Bank = 'interview' | 'aptitude';
export type Mode = 'browse' | 'flashcards' | 'quiz';
export type Status = 'new' | 'review' | 'mastered';

/** A unified shape both banks map onto for the shared card/flashcard/quiz views. */
export interface PrepItem {
  id: string;
  bank: Bank;
  company: string;
  group: string;               // category (interview) or section (aptitude)
  role: string | null;
  question: string;
  /** Markdown shown above options (MCQ table/sub-question), if any. */
  promptMarkdown: string | null;
  options: AptitudeOption[] | null;
  /** The reveal body: model answer (interview/open) or worked solution (mcq). */
  answerMarkdown: string;
  source: string | null;
  topic: string | null;
  isMcq: boolean;
}
